defmodule GithubEx.Repositories.Repository do
  @moduledoc """
  Representation of a Github repository.

  It is the main entity in Github which contains the most important information
  about a project.
  """
  defstruct [
    :labels_url,
    :keys_url,
    :fork,
    :owner,
    :hooks_url,
    :id,
    :teams_url,
    :full_name,
    :git_commits_url,
    :default_branch,
    :downloads_url,
    :stargazers_url,
    :blobs_url,
    :collaborators_url,
    :parent,
    :node_id,
    :watchers_count,
    :notifications_url,
    :compare_url,
    :trees_url,
    :clone_url,
    :has_downloads,
    :subscription_url,
    :url,
    :statuses_url,
    :milestones_url,
    :network_count,
    :svn_url,
    :events_url,
    :updated_at,
    :created_at,
    :html_url,
    :archived,
    :allow_forking,
    :pulls_url,
    :mirror_url,
    :source,
    :has_projects,
    :has_wiki,
    :topics,
    :language,
    :contributors_url,
    :web_commit_signoff_required,
    :issue_events_url,
    :forks,
    :merges_url,
    :subscribers_count,
    :deployments_url,
    :visibility,
    :assignees_url,
    :git_url,
    :forks_url,
    :tags_url,
    :open_issues,
    :size,
    :pushed_at,
    :issues_url,
    :homepage,
    :private,
    :disabled,
    :forks_count,
    :git_tags_url,
    :archive_url,
    :comments_url,
    :has_pages,
    :issue_comment_url,
    :branches_url,
    :description,
    :subscribers_url,
    :stargazers_count,
    :license,
    :commits_url,
    :has_issues,
    :temp_clone_token,
    :git_refs_url,
    :ssh_url,
    :releases_url,
    :is_template,
    :name,
    :languages_url,
    :open_issues_count,
    :contents_url,
    :watchers
  ]

  @type t :: %__MODULE__{
          labels_url: String.t(),
          keys_url: String.t(),
          fork: boolean(),
          owner: String.t(),
          hooks_url: String.t(),
          id: integer(),
          teams_url: String.t(),
          full_name: String.t(),
          git_commits_url: String.t(),
          default_branch: String.t(),
          downloads_url: String.t(),
          stargazers_url: String.t(),
          blobs_url: String.t(),
          collaborators_url: String.t(),
          parent: any(),
          node_id: String.t(),
          watchers_count: integer(),
          notifications_url: String.t(),
          compare_url: String.t(),
          trees_url: String.t(),
          clone_url: String.t(),
          has_downloads: boolean(),
          subscription_url: String.t(),
          url: String.t(),
          statuses_url: String.t(),
          milestones_url: String.t(),
          network_count: integer(),
          svn_url: String.t(),
          events_url: String.t(),
          updated_at: NaiveDateTime.t(),
          created_at: NaiveDateTime.t(),
          html_url: String.t(),
          archived: boolean(),
          allow_forking: boolean(),
          pulls_url: String.t(),
          mirror_url: String.t(),
          source: any(),
          has_projects: boolean(),
          has_wiki: boolean(),
          topics: any(),
          language: String.t(),
          contributors_url: String.t(),
          web_commit_signoff_required: boolean(),
          issue_events_url: String.t(),
          forks: integer(),
          merges_url: String.t(),
          subscribers_count: integer(),
          deployments_url: String.t(),
          visibility: String.t(),
          assignees_url: String.t(),
          git_url: String.t(),
          forks_url: String.t(),
          tags_url: String.t(),
          open_issues: integer(),
          size: integer(),
          pushed_at: NaiveDateTime.t(),
          issues_url: String.t(),
          homepage: String.t(),
          private: boolean(),
          disabled: boolean(),
          forks_count: integer(),
          git_tags_url: String.t(),
          archive_url: String.t(),
          comments_url: String.t(),
          has_pages: boolean(),
          issue_comment_url: String.t(),
          branches_url: String.t(),
          description: String.t(),
          subscribers_url: String.t(),
          stargazers_count: integer(),
          license: any(),
          commits_url: String.t(),
          has_issues: boolean(),
          temp_clone_token: any(),
          git_refs_url: String.t(),
          ssh_url: String.t(),
          releases_url: String.t(),
          is_template: boolean(),
          name: String.t(),
          languages_url: String.t(),
          open_issues_count: integer(),
          contents_url: String.t(),
          watchers: integer()
        }
end
